# Used for "Stock" security_type -- see https://iexcloud.io/docs/api/
iex_token = "pk_tokenstring"

# Used for "Fund" security_type -- see https://www.alphavantage.co/documentation
av_token = "apikey"

[[porfolio]]
name = "Stocks"
show_dividends = true

    [[portfolio.stock]]
    name = "Vanguard"
    security_type = "Fund"
    section = "Fund"
    ticker = "VASGX"
    account = "Assets:Investments:TD Ameritrade:Invested:Fund:VASGX"
    shares = 3000

    [[portfolio.stock]]
    name = "S&P 500"
    security_type = "Stock"
    section = "ETF"
    ticker = "IVV"
    account = "Assets:Investments:TD Ameritrade:Invested:ETF:IVV"
    shares = 3000

    [[portfolio.stock]]
    name = "S&P 500 High Div"
    security_type = "Stock"
    section = "ETF"
    ticker = "SPHD"
    account = "Assets:Investments:TD Ameritrade:Invested:ETF:SPHD"
    shares = 3000

[[portfolio]]
name = "Crypto Holdings"

    [[portfolio.stock]]
    name = "Litecoin"
    security_type = "Crypto"
    section = "LTC"
    ticker = "LTC-USD"
    account = "Assets:Investments:Crypto:LTC"
    shares = 10
